### ISSUE TITLE
another use if this:

### ISSUE THREAD

**Issue by duaneellissd** [m3y54m/Embedded-Engineering-Roadmap#1]
older browsers provide an image map.

it would be interesting to be able to add comments to stuff.

ie click on (or hover) something and you get more details.

another is using a product and map that product to the technologies involved with that product.

an example might be audio signal processing or ble tooth speaker stuff - it might include dsp stuff for audio processing.

in contrast a glucose ble device (ie dexcom-5) uses other sensors

the idea is to take a common product and list the types of technologies used

i do not know a good way to do this its just an idea

**Comment by m3y54m** [comment]
It is a brilliant idea but very difficult to implement for me. Unfortunately I don't have required skills for it.

Thanks anyway
