### ISSUE TITLE
Cross Check of Information Required on Embedded-Engineering-Roadmap.vsdx  page 

### ISSUE THREAD

**Issue by quicksystems-auto** [m3y54m/Embedded-Engineering-Roadmap#11]
Dear Sirs, 

This is nice summary page in the file: Embedded-Engineering-Roadmap.vsdx

However please verify few things.

1) I Operating Systems Section / Block there are U-Boot, BuildBoot / Yocto and QT are present.
Those elements are not Operating System. 
- QT is HMI Engine
- BuildBoot / Yocto  are elements of  CI/CD
- U-Boot is independent   boot loader 

2) I would recommend to have separate item (block) named SW Integration Dev Ops / CI / CD  

Best Regards,
Sergey

**Comment by m3y54m** [comment]
Dear Sergey,

Thank you for your insightful feedback. I appreciate you taking the time to carefully review the summary page and providing valuable suggestions.

1. I understand your point about U-Boot, BuildBoot/Yocto, and QT not being operating systems themselves. However, I would like to clarify that placing these components under the Operating Systems section does not imply they are operating systems. Rather, I have chosen to group them under this heading to provide a comprehensive overview of the essential tools and technologies involved in developing embedded applications running on operating systems, such as Linux.

2. Regarding your suggestion to create a separate item for SW Integration DevOps / CI/CD. "CI/CD Pipelines" is already included in the "Testing" section. Could you please clarify your point further? Are you suggesting that it should not be included within the "Testing" section? or you suggest to change its title from "CI/CD Pipelines" to "SW Integration DevOps / CI/CD"?

Sincerely,
Meysam
