### ISSUE TITLE
Broken Flash and Block File Systems links

### ISSUE THREAD

**Issue by alex-berliner** [m3y54m/Embedded-Engineering-Roadmap#14]
https://github.com/m3y54m/Embedded-Engineering-Roadmap#-file-systems

[📝 Flash filesystems](https://hugh712.gitbooks.io/embeddedsystem/content/flash_filesystems.html) 
https://hugh712.gitbooks.io/embeddedsystem/content/flash_filesystems.html

[📝 Block filesystems](https://hugh712.gitbooks.io/embeddedsystem/content/block_filesystems.html)
https://hugh712.gitbooks.io/embeddedsystem/content/block_filesystems.html

Thanks for making a great resource!

**Comment by m3y54m** [comment]
Thanks for informing but I checked the links and they are okay. Would you please open the links using another device or using another internet connection and see if they are broken in that case?

**Comment by alex-berliner** [comment]
It's working now!
