### ISSUE TITLE
Adding Linting and GitHub Releases

### ISSUE THREAD

**Issue by ScottGibb** [m3y54m/Embedded-Engineering-Roadmap#36]
HI There,

Ive really enjoyed the guide. Been using it over the last year or so and sending to others!

How would you feel about adding the following CI Workflows

- Linting, Running a simple Markdownlint to ensure the guide all has the same standard going forward. Can be triggered on pull requests/pushes
- GitHub Release stage on a tag. We can have another flow/stage that will trigger a release on a tag if the linting passes. It means on the maintainer perspective, all they have to do is push a tag when ready.

If this is something that your interested in,  i'm happy to put together a workflow for the project :)

**Comment by ScottGibb** [comment]
Suggest PR is here: https://github.com/m3y54m/Embedded-Engineering-Roadmap/pull/38

**Comment by m3y54m** [comment]
Good idea. Thanks!
