### ISSUE TITLE
Radio & Mesh, Comms. Protocols

### ISSUE THREAD

**Issue by ajlennon** [m3y54m/Embedded-Engineering-Roadmap#4]
You might also consider adding :

# Radio

- Bluetooth BLE (as opposed to Bluetooth classic), Bluetooth mesh etc.
- GSM cellular including 5G and NB-IoT
- Mesh networking stacks (e.g. OpenThread and Matter)
- Sub GHz standards

# Positioning

- UWB
- GNSS

# Protocols

- MQTT, MQTT-SN, CoAP
- Protocol Buffers (ProtoBuf)

**Comment by m3y54m** [comment]
Thank you so much for so many constructive suggestions. However, the main focus of this roadmap is to highlight the most important topics.

The main audience for this roadmap is people who are new to this field. The topics you mentioned not only fail to assist beginners but also cause frustration and confusion. I would prefer to keep the roadmap simple and as concise as possible.

Anyway I think cellular networks are important enough to be added to the roadmap.

**Comment by ajlennon** [comment]
Not a problem at all - I disagree - these are absolutely core to embedded systems, but it's your decision :)
